version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - MONGOURL=mongodb://mongo:27017/pixelmobails
      - NODE_ENV=production
      - SESSION_SECRET=your_super_secret_key
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
